# Generated by Django 5.2.8 on 2025-12-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
