# Generated by Django 5.2.8 on 2025-12-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0004_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastCost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
