# Generated by Django 4.2.27 on 2025-12-07 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0008_alter_ingredient_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sweet_princing_v2_recipe.recipe'),
        ),
    ]
