# Generated by Django 4.2.27 on 2025-12-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0009_alter_product_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='sweet_princing_v2_recipe.product'),
            preserve_default=False,
        ),
    ]
