# Generated by Django 4.2.27 on 2025-12-07 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0010_remove_product_recipe_recipe_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unitOfMeasure', models.SmallIntegerField(choices=[(1, 'Quilograma'), (2, 'Grama'), (3, 'Miligrama'), (4, 'Litro'), (5, 'Mililitro'), (6, 'Colher de chá'), (7, 'Colher de sopa'), (8, 'Colher de sobremesa'), (9, 'Xícara'), (10, 'Unidade'), (11, 'Pitada'), (12, 'Copo americano'), (13, 'Concha')], default=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sweet_princing_v2_recipe.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sweet_princing_v2_recipe.recipe')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
    ]
