# Generated by Django 4.2.27 on 2025-12-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0014_ingredient_unitofmeasure_alter_recipe_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='totalCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
