# Generated by Django 4.2.27 on 2025-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_princing_v2_recipe', '0016_recipe_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeitem',
            name='unitCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
